-- NGO DANG TAN
-- EMAIL: 24210173@ms.uit.edu.vn

CREATE DATABASE QLBH
CREATE DATABASE QLGV
USE QLBH
USE QLGV

DROP DATABASE QLBH -- XOA BO DATABASE

--QLBH
-- CAU 1: Tạo các quan hệ và khai báo các khóa chính, khóa ngoại của quan hệ.
CREATE TABLE KHACHHANG(
    MAKH CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40) NOT NULL,
    DCHI VARCHAR(50),
    SODT VARCHAR(20) NOT NULL,
    NGSINH SMALLDATETIME CHECK (NGSINH > '01-01-1900'),
    DOANHSO MONEY,
    NGDK SMALLDATETIME
);

CREATE TABLE NHANVIEN(
    MANV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40) NOT NULL,
    SODT VARCHAR(20)  NOT NULL,
    NGVL SMALLDATETIME,
);

CREATE TABLE SANPHAM(
    MASP CHAR(4) PRIMARY KEY,
    TENSP VARCHAR(40) NOT NULL,
    DVT VARCHAR(20),
    NUOCSX VARCHAR(40),
    GIA MONEY
);

CREATE TABLE HOADON(
    SOHD INT PRIMARY KEY,
    NGHD SMALLDATETIME,
    MAKH CHAR(4) REFERENCES KHACHHANG(MAKH),
    MANV CHAR(4) REFERENCES NHANVIEN(MANV),
    TRIGIA MONEY
);

CREATE TABLE CTHD(
    SOHD INT,
    MASP CHAR(4),
    SL INT,
    PRIMARY KEY (SOHD, MASP),
    FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

--Cau 2: Thêm vào thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM.
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20);

--CAU 3: Thêm vào thuộc tính LOAIKH có kiểu dữ liệu là tinyint cho quan hệ KHACHHANG.
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT;

--CAU 4: Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100).
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

--CAU 5: Xóa thuộc tính GHICHU trong quan hệ SANPHAM.
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

--CAU 6: Làm thế nào để thuộc tính LOAIKH trong quan hệ KHACHHANG có thể lưu các giá trị là: “Vang lai”, “Thuong xuyen”, “Vip”…
ALTER TABLE KHACHHANG
ADD LOAIKH VARCHAR(20) CHECK (LOAIKH IN ('Vang Lai', 'Thuong xuyen', 'Vip'));